apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 9999999
      volumeMounts:
        - name: regcred
          mountPath: /kaniko/.docker
  volumes:
    - name: regcred
      projected:
        sources:
          - secret:
              name: regcred
              items:
                - key: .dockerconfigjson
                  path: config.json
